options(repos='http://cran.rstudio.com/')
install.packages("ggpubr")
install.packages("gridExtra")
install.packages("DescTools")
install.packages("GenomicRanges")
install.packages("ks")
install.packages("ggrepel")
